# This is a basic workflow to help you get started with Actions

name: CI


on:
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: 
      - self-hosted
      - label-1
    
    steps:
      - uses: actions/checkout@v3

      
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run:
          echo Hello, world!
          sleep 15
          echo Goodbye!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run:
          echo "${{ github.workspace}}"
          
          echo test, and deploy your project.
